name: Test SPHINCS+ Post-Quantum Digital Signature Scheme

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup Google-Test
      run: |
        pushd ~
        git clone https://github.com/google/googletest.git -b v1.14.0
        pushd googletest
        mkdir build
        pushd build
        cmake .. -DBUILD_GMOCK=OFF
        make
        sudo make install
        popd
        popd
        popd
    - name: Execute Tests on ${{matrix.os}}
      run: make -j
